apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app1
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: production
  chart:
    spec:
      chart: app1-helm-chart  # Corrected path
      sourceRef:
        kind: GitRepository
        name: flux-system
valuesFrom:
  - kind: GitRepository
    name: flux-system
    valuesKey: "helm-charts/app1-helm-chart/values-production.yaml"