apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app1
  namespace: app1-namespace
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm-charts/app1  # Path inside the GitOps repo
      sourceRef:
        kind: GitRepository
        name: gitops-repo
      interval: 5m
  values:
    replicaCount: 2
    image:
      repository: my-app
      tag: "latest"
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "512Mi"

