apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app1
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: production
  chart:
    spec:
      chart: ./helm-charts/app1-helm-chart  # Corrected path
      sourceRef:
        kind: GitRepository
        name: flux-system
  valuesFiles:
    - "helm-charts/app1-helm-chart/values-production.yaml"