replicaCount: 2

image:
  registry: "479701439711.dkr.ecr.us-east-1.amazonaws.com"
  repository: "testassignment/my-spring-boot-repo"
  tag: "latest"
  pullPolicy: "IfNotPresent"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hostname: myapp.example.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

aws:
  accountId: "479701439711"

serviceAccount:
  create: true
  name: "ecr-sa"
  iamRoleName: "ECRAccessRole"

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1
