apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app1
  namespace: staging
spec:
  interval: 1m
  targetNamespace: staging
  chart:
    spec:
      chart: ./helm-charts/app1-helm-chart  # Corrected path
      sourceRef:
        kind: GitRepository
        name: flux-system