apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production
  namespace: flux-system
spec:
  interval: 1m
  path: ./production/app1  # Path where helmrelease.yaml is located
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: production
